Link da pesquisa:

https://forms.gle/f5BJZM8dDdKdQLoe8

In [10]:
import numpy as np
import pandas as pd

In [21]:
dados = pd.read_csv('/content/drive/MyDrive/ESTATISTICA-APLICADA/Aula-4/pesquisa_1.csv',
                      sep=',', encoding='UTF-8')
dados

,Carimbo de data/hora,Qual o seu RA?,Qual a sua altura?,Qual a sua cor favorita?,Qual o número de seu calçado?
0,2023/04/26 4:53:07 PM GMT-3,1110482212025,1.85,Cinza,44
1,2023/04/26 4:53:11 PM GMT-3,1110482212030,1.80,laranja,44
2,2023/04/26 4:53:14 PM GMT-3,1110482212009,1.63,vermelho,39
3,2023/04/26 4:53:37 PM GMT-3,1110482212036,1.56,azul,37
4,2023/04/26 4:53:55 PM GMT-3,1110482222039,1.90,azul,42
5,2023/04/26 4:54:04 PM GMT-3,1110482212004,1.83,laranja,40
6,2023/04/26 4:54:06 PM GMT-3,1110482212026,1.64,vermelho,39
7,2023/04/26 4:54:08 PM GMT-3,1110482212002,1.88,vermelho,42
8,2023/04/26 4:54:17 PM GMT-3,1110482212035,1.85,roxo,43-44
9,2023/04/26 4:54:25 PM GMT-3,111048212031,1.50,laranja,35
10,2023/04/26 4:54:45 PM GMT-3,1110482212016,1.74,Verde,35
11,2023/04/26 4:54:58 PM GMT-3,1110482212001,"1,70",Preto,42
12,2023/04/26 4:55:14 PM GMT-3,1110482212019,1.68,Branco,37
13,2023/04/26 4:55:37 PM GMT-3,1110482212018,1.64,cinza,36
14,2023/04/26 4:55:51 PM GMT-3,1110482212024,1.65,preto,38
15,2023/04/26 4:55:59 PM GMT-3,1110482212021,1.70,preto,40/41
16,2023/04/26 4:56:05 PM GMT-3,1110482212039,1.84,preto,43
17,2023/04/26 4:56:25 PM GMT-3,1110482212029,1.81,azul,42
18,2023/04/26 4:56:28 PM GMT-3,1110482212011,1.69,roxo,38
19,2023/04/26 4:56:34 PM GMT-3,1110482212007,1.65,preto,40
20,2023/04/26 4:56:42 PM GMT-3,1110482212022,1.55,preto,36
21,2023/04/26 4:57:57 PM GMT-3,1110482212043,1.55,verde,35

In [22]:
dados.shape

(22, 5)

## **TRATAMENTO DOS DADOS**

In [23]:
# Excluir coluna
dados1 = dados.drop(columns=['Carimbo de data/hora'])
dados1.head(3)

,Qual o seu RA?,Qual a sua altura?,Qual a sua cor favorita?,Qual o número de seu calçado?
0,1110482212025,1.85,Cinza,44
1,1110482212030,1.80,laranja,44
2,1110482212009,1.63,vermelho,39

In [24]:
# Renomear colunas
dados1 = dados1.rename(columns={'Qual a sua altura?': 'altura(m)'})
dados1.head(2)

,Qual o seu RA?,altura(m),Qual a sua cor favorita?,Qual o número de seu calçado?
0,1110482212025,1.85,Cinza,44
1,1110482212030,1.80,laranja,44

In [25]:
dados1.rename(columns={'Qual o seu RA?': 'ra','Qual a sua cor favorita?':'cor_favorita'},inplace=True)
dados1

               ra altura(m) cor_favorita Qual o número de seu calçado?
0   1110482212025      1.85        Cinza                            44
1   1110482212030      1.80      laranja                            44
2   1110482212009      1.63     vermelho                            39
3   1110482212036      1.56         azul                            37
4   1110482222039      1.90         azul                            42
5   1110482212004      1.83      laranja                            40
6   1110482212026      1.64     vermelho                            39
7   1110482212002      1.88     vermelho                            42
8   1110482212035      1.85         roxo                         43-44
9    111048212031      1.50      laranja                            35
10  1110482212016      1.74        Verde                            35
11  1110482212001      1,70        Preto                            42
12  1110482212019      1.68       Branco                            37
13  1110482212018      1.64        cinza                            36
14  1110482212024      1.65        preto                            38
15  1110482212021      1.70        preto                         40/41
16  1110482212039      1.84        preto                            43
17  1110482212029      1.81         azul                            42
18  1110482212011      1.69         roxo                            38
19  1110482212007      1.65        preto                            40
20  1110482212022      1.55        preto                            36
21  1110482212043      1.55        verde                            35

In [26]:
# Valores faltantes (missing)
dados1.isnull().sum()

ra                               0
altura(m)                        0
cor_favorita                     0
Qual o número de seu calçado?    0
dtype: int64

In [27]:
# Analisando as variáveis
dados1.dtypes

ra                                int64
altura(m)                        object
cor_favorita                     object
Qual o número de seu calçado?    object
dtype: object

In [28]:
dados1.head(23)

               ra altura(m) cor_favorita Qual o número de seu calçado?
0   1110482212025      1.85        Cinza                            44
1   1110482212030      1.80      laranja                            44
2   1110482212009      1.63     vermelho                            39
3   1110482212036      1.56         azul                            37
4   1110482222039      1.90         azul                            42
5   1110482212004      1.83      laranja                            40
6   1110482212026      1.64     vermelho                            39
7   1110482212002      1.88     vermelho                            42
8   1110482212035      1.85         roxo                         43-44
9    111048212031      1.50      laranja                            35
10  1110482212016      1.74        Verde                            35
11  1110482212001      1,70        Preto                            42
12  1110482212019      1.68       Branco                            37
13  1110482212018      1.64        cinza                            36
14  1110482212024      1.65        preto                            38
15  1110482212021      1.70        preto                         40/41
16  1110482212039      1.84        preto                            43
17  1110482212029      1.81         azul                            42
18  1110482212011      1.69         roxo                            38
19  1110482212007      1.65        preto                            40
20  1110482212022      1.55        preto                            36
21  1110482212043      1.55        verde                            35

In [29]:
dados1['altura(m)'] = dados1['altura(m)'].apply(lambda x: x.replace(',','.'))
dados1

               ra altura(m) cor_favorita Qual o número de seu calçado?
0   1110482212025      1.85        Cinza                            44
1   1110482212030      1.80      laranja                            44
2   1110482212009      1.63     vermelho                            39
3   1110482212036      1.56         azul                            37
4   1110482222039      1.90         azul                            42
5   1110482212004      1.83      laranja                            40
6   1110482212026      1.64     vermelho                            39
7   1110482212002      1.88     vermelho                            42
8   1110482212035      1.85         roxo                         43-44
9    111048212031      1.50      laranja                            35
10  1110482212016      1.74        Verde                            35
11  1110482212001      1.70        Preto                            42
12  1110482212019      1.68       Branco                            37
13  1110482212018      1.64        cinza                            36
14  1110482212024      1.65        preto                            38
15  1110482212021      1.70        preto                         40/41
16  1110482212039      1.84        preto                            43
17  1110482212029      1.81         azul                            42
18  1110482212011      1.69         roxo                            38
19  1110482212007      1.65        preto                            40
20  1110482212022      1.55        preto                            36
21  1110482212043      1.55        verde                            35

In [30]:
dados1.dtypes

ra                                int64
altura(m)                        object
cor_favorita                     object
Qual o número de seu calçado?    object
dtype: object

In [31]:
dados1['altura(m)'] = dados1['altura(m)'].astype(float)
dados1.dtypes

ra                                 int64
altura(m)                        float64
cor_favorita                      object
Qual o número de seu calçado?     object
dtype: object

In [32]:
dados1['cor_favorita'] = dados1.cor_favorita.str.lower()
dados1.head(23)

               ra  altura(m) cor_favorita Qual o número de seu calçado?
0   1110482212025       1.85        cinza                            44
1   1110482212030       1.80      laranja                            44
2   1110482212009       1.63     vermelho                            39
3   1110482212036       1.56         azul                            37
4   1110482222039       1.90         azul                            42
5   1110482212004       1.83      laranja                            40
6   1110482212026       1.64     vermelho                            39
7   1110482212002       1.88     vermelho                            42
8   1110482212035       1.85         roxo                         43-44
9    111048212031       1.50      laranja                            35
10  1110482212016       1.74        verde                            35
11  1110482212001       1.70        preto                            42
12  1110482212019       1.68       branco                            37
13  1110482212018       1.64        cinza                            36
14  1110482212024       1.65        preto                            38
15  1110482212021       1.70        preto                         40/41
16  1110482212039       1.84        preto                            43
17  1110482212029       1.81         azul                            42
18  1110482212011       1.69         roxo                            38
19  1110482212007       1.65        preto                            40
20  1110482212022       1.55        preto                            36
21  1110482212043       1.55        verde                            35

In [33]:
import plotly.express as px
bolhas = px.scatter(dados1, x="cor_favorita", y="altura(m)")
bolhas.show()

In [34]:
dados1.to_csv('pesquisa_tratada_exemplo.csv', sep=',', encoding='UTF-8', index = False)

In [35]:
dados1.to_csv('/content/drive/MyDrive/ESTATISTICA-APLICADA/Aula-4/pesquisa_tratada_exemplo.csv', sep=',', encoding='UTF-8', index = False)